pipeline {
    //largely generated by google ai, then manually typed
    agent any
    stages {
        stage('Build') {
            steps {
                echo "Building project..."
                echo "Nothing to build!"
                // sh 'python3 sample_packets/unit-test.py'
            }
        }
        stage('Test') {
            steps {
                echo "Running unit test!"
                sh 'python3 sample_packets/unit-test.py'
            }
        }
        stage('Deploy') {
            steps {
                echo "Deploying app!"
                echo "Nothing to deploy!"
            }
        }
    }
    post {
        always {
            echo 'Jenkins Jenkined'
        }
        success {
            echo 'Tests succedeed!'
        }
        failure {
            echo 'Tests failed successfully!'
        }
    }
}